### ISSUE TITLE
Updating transactions in YNAB once cleared

### ISSUE THREAD

**Issue by PromoFaux** [syncforynab/fintech-to-ynab#162]
Just back from a lovely holiday, and when going to reconcile on YNAB, I noticed that there were some differences in transaction values.

This is obviously because the initial transaction in Monzo is a placeholder until the exchange rate settlings, however what I ended up with was a ton of transactions that had a few pence difference between YNAB and Monzo. I ended up just letting YNAB do an auto-adjustment on reconciliation, but it got me to wondering...

Is it possible for fintech-to-ynab to update a transaction on YNAB once it gets newer information? Should it already be doing this and I've misconfigured? Is it worth me looking at this from a code point of view (I don't know `ruby`!), or has this already been attempted and ruled out as not possible?

**Comment by scottrobertson** [comment]
If you are using webhooks, there is no way to do it sadly.

**Comment by PromoFaux** [comment]
That _is_ a shame. I've not looked into the YNAB API too much, figured you would know enough to be able to answer my question!

Presumably Monzo does not fire a webhook on Transaction update?

**Comment by scottrobertson** [comment]
@PromoFaux Correct, this is due to Monzo not sending update webhooks.

We support this on Sync for YNAB when connected via TrueLayer.

I will look at adding support for it here, but the way fintech-to-ynab is built, it may make it quite a bit more difficult.

**Comment by PromoFaux** [comment]
In the mean time, I may look into Sync for YNAB, though I do like the ability to self-host, so perhaps I will just put up with the limits of webhooks :) It's not like I go overseas so often that this is a nightmare!

Thanks for your response.

**Comment by scottrobertson** [comment]
Yeah it's a bit of a pain when traveling. I still suffer from the same thing as i use webhooks on Sync for YNAB too (because they are just so much nicer overall).

Will see what i can do :)

**Comment by colophonemes** [comment]
I had this problem too (and I also had problems with the Ruby Starling lib dependency in `fintech-to-ynab`), so I wrote my own script to handle this: https://github.com/colophonemes/starling-to-ynab

**Comment by scottrobertson** [comment]
If someone wants to PR this, feel free, but I am going to close this as it's not something I will be adding due to time.

Sync for YNAB does handle this automatically, as you can connect Webhooks + Open Banking for Monzo, so if you want that, you can use that.
