### ISSUE TITLE
Help with Docker

### ISSUE THREAD

**Issue by add1989** [syncforynab/fintech-to-ynab#247]
Hi All,

I don't know if I'm being stupid here, but how do I find out what port the Docker container uses?

I've tried to run it with various different combinations but can't seem to figure it out:

```
sudo docker run -d \
 --name fintech2ynab \
 --restart=unless-stopped \
 -p 8080:8080 \
 -e YNAB_ACCESS_TOKEN="xxxx" \
 -e YNAB_BUDGET_ID="xxxx" \
 fintechtoynab/fintech-to-ynab
```

To help new users, could we perhaps but some sample docker commands in the getting started guide?

**Comment by scottrobertson** [comment]
Hey

Rails/puma uses port 3000 by default

**Comment by add1989** [comment]
When I fork the project it doesn't bring the wiki with it, so I can't find a way to edit that.

I will just leave my finished command here in case anybody searches for it:

```
sudo docker run -d \
 --name fintech2ynab \
 --restart=unless-stopped \
 -p <host port number>:3000 \
 -e YNAB_ACCESS_TOKEN="xxxx" \
 -e YNAB_BUDGET_ID="xxxx" \
 -e YNAB_MONZO_ACCOUNT_ID="xxxx"
 fintechtoynab/fintech-to-ynab
```
