### ISSUE TITLE
Monzo Webhook Error - account must be formatted as a uuid (universally unique identifier)

### ISSUE THREAD

**Issue by totalitarian** [syncforynab/fintech-to-ynab#274]
Hi,

I tried setting up the monzo webhook but get this error on heroku, any ideas?

`YNAB::Client.create_transaction Response: {"error":{"id":"400","name":"bad_request","detail":"account must be formatted as a uuid (universally unique identifier)"}}`

**Comment by scottrobertson** [comment]
Can you send me the ynab account id environment variable you used?

**Comment by totalitarian** [comment]
I don't think it asked me for one, only

- YNAB_ACCESS_TOKEN
- YNAB_BUDGET_ID
- URL_SECRET

**Comment by scottrobertson** [comment]
You will need YNAB_MONZO_ACCOUNT_ID too as per https://github.com/syncforynab/fintech-to-ynab/wiki/import:-Monzo

**Comment by totalitarian** [comment]
Do I also need to do the #import section too? I'm not interested in importing old transactions just new ones pushed via the webhook

**Comment by scottrobertson** [comment]
> Do I also need to do the #import section too? I'm not interested in importing old transactions just new ones pushed via the webhook

You don't have to do it if you don't want to :)

**Comment by totalitarian** [comment]
Perfect, thanks very much!

**Comment by scottrobertson** [comment]
@totalitarian so all sorted? Am I ok to close this?

**Comment by totalitarian** [comment]
Yes please
