### ISSUE TITLE
Starling Retiring existing Webhooks - potential issue?

### ISSUE THREAD

**Issue by GazFranklin** [syncforynab/fintech-to-ynab#294]
Apologies if this is the wrong place for this but it looks like Starling are retiring the current webhooks and replacing them with new ones. 

The email I received from Starling says the current webhooks will "start to be disconnected from 13th July 2021". 

Any chance fintech-to-ynab will be adding support for the V2 webhooks? I'd do it myself and submit a PR but my Ruby skills are essentially zero.

**Comment by scottrobertson** [comment]
If I get some time, I will look at adding support, but I am not sure when that will be unfortunately.

**Comment by BraXzy** [comment]
I'd also massively appreciate this update - has anyone been able to look into it?

**Comment by GazFranklin** [comment]
Hi @scottrobertson, 

I got this working with Starling's V2 webhooks and so far all seems well. 

As I said before I am **not** a Ruby dev so the code isn't the prettiest (some of your existing logic seems to be inside a Gem and I had no idea how to edit one of those!), but it works!

Would you be free any time soon to review?

**Comment by scottrobertson** [comment]
Hey @GazFranklin 

If you submit it as PR I can take a look ASAP.

**Comment by GazFranklin** [comment]
Done (I think!) #310

**Comment by GazFranklin** [comment]
@scottrobertson as you've approved my PR, I guess we can close this? :-) 

Not sure I can update the Wiki, but (once released) all people need to do it create a V2 webhook, of type "feed item" with the same Payload URL as the old V1 implementation (i.e. https://someone-fintech-to-ynab.herokuapp.com/starling)

**Comment by scottrobertson** [comment]
@GazFranklin thanks! Updated the Wiki too: https://github.com/syncforynab/fintech-to-ynab/wiki/import:-Starling-Bank
