### ISSUE TITLE
V1 API no longer available?

### ISSUE THREAD

**Issue by kurtpeniket** [syncforynab/fintech-to-ynab#301]
I've followed everything on the readme and I'm pretty sure I've set up webhooks and tokens correctly but nothing seems to be updating. When I do a manual import (`heroku run ./bin/import starling --token [Starling Token] --ynab_account_id [YNAB Account ID]`), I get a 404 saying that the V1 API is no longer available? 

Sorry if this is a dumb issue to open, I'm not very experienced with this kind of thing!

**Comment by scottrobertson** [comment]
Starling are deprecating V1, and we do not support V2 at this time. If someone wants to add support, feel free, as I likely won't have the time/motivation to do it for a while.

**Comment by kurtpeniket** [comment]
> Starling are deprecating V1, and we do not support V2 at this time. If someone wants to add support, feel free, as I likely won't have the time/motivation to do it for a while.

Ok thanks @scottrobertson , I'll take a look at the docs. Might be something I can work on myself if it's not too difficult!
