### ISSUE TITLE
Trying to run on Heroku

### ISSUE THREAD

**Issue by daveydave** [syncforynab/fintech-to-ynab#302]
Hi Scott. I'm following your getting started doc on setting up with Heroku. When I click "Deploy App" it fails, saying:

  The Ruby version you are trying to install does not exist on this stack.
 !     
 !     You are trying to install ruby-2.5.1 on heroku-20

Would you know how to make this work?

**Comment by scottrobertson** [comment]
I am not sure why it's trying to install 2.5.1, as we specify a higher version. This looks like it's doing the same as happened in https://github.com/syncforynab/fintech-to-ynab/issues/273 and seems to be an intermittent issue on the Heroku side.

**Comment by daveydave** [comment]
Interesting. I don't know anything about development, but I'll reach out to Heroku and see if they might be able to help. Thanks Scott.

**Comment by olane** [comment]
FWIW, I just got this too. Workaround for me was to just go straight to forking the repo and setting up a new app based on that fork, which just worked. Had to go manually create the correct environment variables but then it all worked fine.

**Comment by daveydave** [comment]
I'll give that a try. Thanks!

**Comment by daveydave** [comment]
That worked just as you said! One thing I'm a little concerned about is that the transactions may come over in a European date format vs US format, and if so will YNAB know to convert that? When I export statements from the Monzo app, the date is in European format (even though I'm on Monzo US). Something I called out to them and they'll correct eventually, but in this case it may mess up YNAB. We'll see!
