### ISSUE TITLE
Duplicate Monzo transactions using webhook

### ISSUE THREAD

**Issue by QuaCKeReD** [syncforynab/fintech-to-ynab#381]
Hi
Just setup Heroku app for webhook feed from Monzo to YNAB. 

Am getting duplicate transactions - once from webhook and another from YNAB direct import.

**Comment by scottrobertson** [comment]
This is expected. The 2 systems cannot work together in that way unfortunately.

**Comment by QuaCKeReD** [comment]
Hi,
When you say the 2 systems - is that this service and ynab direct import, or this service and any import?

**Comment by scottrobertson** [comment]
The only way to get webhooks + open banking is to use Sync for YNAB. This script wont work with any other import system.
