### ISSUE TITLE
Bank Requests

### ISSUE THREAD

**Issue by scottrobertson** [syncforynab/fintech-to-ynab#73]
Please comment here with any banks you would like to be supported. If the bank does not have an API, or a way to automatically get the data, we can add support for their CSV format.

If we find a way to implement the bank, we will create a new seperate ticket for it to track it's implementation.

Please submit your request with the following:

- Name of Bank
- Country of Bank
- Do they have an API?
- If not, do they support CSV/QIF exports?

**Comment by scottrobertson** [comment]
Lloyds Bank (#70)

**Comment by rndthoughts** [comment]
Name: Nationwide
Country: UK
API: yes - https://www.nationwide.co.uk/developer/getting-started - but not sure how many hoops you need to jump through!
CSV/QIF exports support: Yes

**Comment by scottrobertson** [comment]
@rndthoughts Nationwide are supported via https://github.com/fintech-to-ynab/fintech-to-ynab/wiki/import:-Teller

**Comment by rndthoughts** [comment]
Oh great, I had no idea!

**Comment by scottrobertson** [comment]
@rndthoughts https://github.com/fintech-to-ynab/fintech-to-ynab#banksfinancial-institutions ;)

**Comment by rndthoughts** [comment]
I guess my confusion was over whether they supported webhooks - but I'm guessing that wasnt mandatory in the open banking spec?

**Comment by scottrobertson** [comment]
Ah right, no webhooks sadly. Teller don't use any of the open banking stuff either.

**Comment by rndthoughts** [comment]
... off to fin-tech we go then :)

**Comment by scottrobertson** [comment]
Using Open banking is unlikely to happen for us, it requires an insane amount of hoops to jump through from what i have seen. I doubt it will ever be suitable for open source without some sort of service inbetween.

**Comment by rndthoughts** [comment]
Understood. Still it's great to use this project with the fin-techs and YNAB while they are still figuring out how to create their budget controls, so thank you!

**Comment by duch11** [comment]
Name: All of the Scandinavian banks
Country: Denmark (but maybe also Sweden, Norway and Finland)
API: https://developer.nordicapigateway.com/
CSV/QIF: not sure

**Comment by lucasomigli** [comment]
Barclays, UK
https://developer.barclays.com/

Tried with Teller.io but they currently have a problem with Barclays API.

**Comment by cmeijburg** [comment]
Name: bunq
Country: Netherlands, Germany, Italy, Spain
API: https://www.bunq.com/developer
CSV: yes, also available. Format: "Date";"Amount";"Account";"Counterparty";"Name";"Description"

Additional api documentation available on https://doc.bunq.com/

**Comment by kot-behemoth** [comment]
I know it’s not strictly a bank, but it’s a very useful feed to auto send to YNAB - American Express. 

- Name of Bank: American Express
- Country of Bank: US
- Do they have an API?: looks like it, but not sure about the extent https://developer.americanexpress.com
- If not, do they support CSV/QIF exports?: yes, both

**Comment by scottrobertson** [comment]
@kot-behemoth it does not look like they have an API for transactions sadly. Perhaps you could send me a sample CSV and i can get that working?

**Comment by kot-behemoth** [comment]
@scottrobertson I can create a separate issue for this, and upload sample data there, so that it doesn’t add noise to this thread. Will do that once I’m not on mobile. Would QFX alongside CSV be helpful?

**Comment by scottrobertson** [comment]
@kot-behemoth all of that would be awesome, thank you.

**Comment by craigy20** [comment]
would it be possible to get Halifax transactions feeding into YNAB. 

Name of Bank: Halifax
Country of Bank: UK
Do they have an API? Yes, https://developer.halifax.co.uk/opendata-v2 
If not, do they support CSV/QIF exports? they do support CSV/QIF exports

**Comment by scottrobertson** [comment]
@craigy20 it would need to be CSV/QIF sadly. UK banks are basically making it impossible for people to get access, let alone getting access for each person that would want to use Fintech to YNAB.

Can you open a ticket with an example Halifax CSV, and i can get that built out for you 👍

**Comment by tibu** [comment]
Name of Bank: Revolut Ltd
    Country of Bank: UK
    Do they have an API?: Only for business
    If not, do they support CSV/QIF exports? No

**Comment by scottrobertson** [comment]
@tibu just to clarify, you want this for the business account?

**Comment by frazzyfin** [comment]
Name: Halifax Bank of Scotland
Country: UK
API: Not that I know of..
CSV/QIF exports support: Yes

**Comment by scottrobertson** [comment]
Thanks @frazzyfin 

Could you provide a sample CSV please?

**Comment by frazzyfin** [comment]
Sure, here you go. 

[01001254_20181011_1102.txt](https://github.com/fintech-to-ynab/fintech-to-ynab/files/2468472/01001254_20181011_1102.txt)

**Comment by scottrobertson** [comment]
Thank you. I will get that added asap.

**Comment by scottrobertson** [comment]
@frazzyfin can you email me at scottymeuk at gmail? i have something that supports HBOS that i could do with some testing.

**Comment by lucasomigli** [comment]
Name: N26
Country: Germany 
API: Yes
CSV Export: Yes 

There's another repo where the connection has been built: 
 
https://github.com/schurig/ynab-bank-importer/wiki/n26

**Comment by mattsson** [comment]
Name: Arbejdernes Landsbank (https://al-bank.dk)
Country: Denmark
API: https://developer.nordicapigateway.com

**Comment by quinnfive** [comment]
Hey man I'd also love to have this working with N26 pretty please. I'm using basically N26 and Revolut Business for 95% of my banking and I find it hard to keep up with YNAB cus it's a pain in the butt to automatically import. If you could get these both working I'll seriously be glad of it. Thanks man! Been hoping for a solution for this for several months, now there's some hope :)

**Comment by RosemaryOrchard** [comment]
I'd love to see you support Tink, they're not a bank - but they collect financial transactions together for their users. This means you could support many more banks without implementing each one yourself immediately. 

Tink
Europe
https://docs.tink.com/enterprise/api/

**Comment by topherredden** [comment]
Tandem CC
https://intercom.help/tandembank/open-banking/how-do-i-access-my-credit-card-data-via-open-banking-psd2-apis

**Comment by scottrobertson** [comment]
@topherredden got a call with Token soon.

**Comment by topherredden** [comment]
That works for me, I'm signed up to syncforynab 👍

**Comment by fosibodu** [comment]
Name of Bank: Nordea 
Country of Bank: Denmark
Do they have an API?: Yes
If not, do they support CSV/QIF exports?: CSV

**Comment by scottrobertson** [comment]
@fosibodu I won't be able to add them here sadly, but I can enable them as a beta on Sync for YNAB if you want to try it out there?

**Comment by scottrobertson** [comment]
@RosemaryOrchard Sadly Tink are not suitable for this project, as they require the user to be present to refresh transactions. This means i would have to send users to Tink every time you wanted to import.

For Sync for YNAB, we use TrueLayer and Saltedge though, we don't directly integrate with banks 👍

**Comment by scottrobertson** [comment]
Launched N26 beta on Sync for YNAB. Going to look at adding it here, but not sure I will do it as so few people use it.

**Comment by exptom** [comment]
Could you add Triodos Current (and savings/isa if possible) Accounts? They have an API: https://developer.triodos.com/

**Comment by idetkov** [comment]
Tinkoff bank https://www.tinkoff.ru/eng/
https://github.com/TinkoffCreditSystems
Russia
Do they have an API? - YES

**Comment by levent** [comment]
Bank: First Direct (same API as HSBC)
Country: UK
API: Yes
CSV/QIF: Yes

I believe this used to be possible with Teller.io

**Comment by scottrobertson** [comment]
@levent unfortunately we are not able to support open banking API's in this project.

**Comment by lukkigi** [comment]
Bank: DKB dkb.de
Country: Germany
API: no
CSV Export: yes

**Comment by PehrGit** [comment]
Name of Bank: Rabobank
Country of Bank: Netherlands, Ireland, New Zealand, Australia, Gernamy, Poland
Do they have an API: Yes, https://developer.rabobank.nl/
CSV Export: yes

**Comment by scottrobertson** [comment]
Hey @PehrGit 

This is sadly not something we can add to the open source project for a number of reasons, but I have made a not for it in syncforynab.com

**Comment by PehrGit** [comment]
> Hey @PehrGit
> 
> This is sadly not something we can add to the open source project for a number of reasons, but I have made a not for it in syncforynab.com

Are those reasons mainly the European legislation for financial service providers?

**Comment by scottrobertson** [comment]
And that there is no storage within this project to store oauth tokens etc.
Adding storage makes deploying this much more complex.

**Comment by scottrobertson** [comment]
Closing this, as it's unlikely that I will be able to add any more banks here, since all are going via Open Banking now, and require storage, and have regulatory requirements for access. Please use syncforynab.com for any banks you want to connect to via Open Banking.
